"""empty message

Revision ID: 48efa7849622
Revises: 64c2b025eb65
Create Date: 2022-01-06 02:13:40.138092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48efa7849622'
down_revision = '64c2b025eb65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_docs', sa.Column('status_text', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_docs', 'status_text')
    # ### end Alembic commands ###
