"""empty message

Revision ID: 4bf319649d0e
Revises: af19218d181a
Create Date: 2021-12-26 20:04:27.487928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf319649d0e'
down_revision = 'af19218d181a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_docs', sa.Column('verified', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_docs', 'verified')
    # ### end Alembic commands ###
