"""empty message

Revision ID: 64c2b025eb65
Revises: 4bf319649d0e
Create Date: 2022-01-05 15:15:35.468430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64c2b025eb65'
down_revision = '4bf319649d0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('timetamp', sa.String(length=50), nullable=True))
    op.add_column('property', sa.Column('timetamp', sa.String(length=50), nullable=True))
    op.add_column('property_docs', sa.Column('timetamp', sa.String(length=50), nullable=True))
    op.add_column('rating', sa.Column('timetamp', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('timetamp', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'timetamp')
    op.drop_column('rating', 'timetamp')
    op.drop_column('property_docs', 'timetamp')
    op.drop_column('property', 'timetamp')
    op.drop_column('plans', 'timetamp')
    # ### end Alembic commands ###
