"""is_used column for validating transaction_code

Revision ID: 9bd13d692aad
Revises: 6278cdf55113
Create Date: 2022-01-08 10:52:54.994982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd13d692aad'
down_revision = '6278cdf55113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_gateway', sa.Column('is_used', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_gateway', 'is_used')
    # ### end Alembic commands ###
