"""changed timestamp to date for subscription status check

Revision ID: f629beffa267
Revises: 9bd13d692aad
Create Date: 2022-01-08 11:01:48.580907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f629beffa267'
down_revision = '9bd13d692aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('end_date', sa.String(length=50), nullable=False))
    op.add_column('subscription', sa.Column('start_date', sa.String(length=50), nullable=False))
    op.drop_column('subscription', 'end_timetamp')
    op.drop_column('subscription', 'start_timetamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('start_timetamp', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('subscription', sa.Column('end_timetamp', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('subscription', 'start_date')
    op.drop_column('subscription', 'end_date')
    # ### end Alembic commands ###
