"""empty message

Revision ID: 65c756b3fc36
Revises: 97cb4eb3b502
Create Date: 2021-06-27 02:49:35.760063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c756b3fc36'
down_revision = '97cb4eb3b502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('property_location', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'property_location')
    # ### end Alembic commands ###
