"""Added businessAccount Column to emulate Admin Functions

Revision ID: 87d20ff10f5c
Revises: 65c756b3fc36
Create Date: 2021-07-02 23:40:00.644371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d20ff10f5c'
down_revision = '65c756b3fc36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('businessAccount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'businessAccount')
    # ### end Alembic commands ###
