"""empty message

Revision ID: 894d4a230782
Revises: 51884c2f9407
Create Date: 2021-06-13 12:44:08.660012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894d4a230782'
down_revision = '51884c2f9407'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_updates', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_updates')
    # ### end Alembic commands ###
