"""Added Relationship btwn the Business Owners/Accounts and their Business- Plans

Revision ID: 94456c5b40c6
Revises: e481c2703d12
Create Date: 2021-07-17 01:03:46.490672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94456c5b40c6'
down_revision = 'e481c2703d12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('businessPlan', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'plans', ['businessPlan'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'businessPlan')
    # ### end Alembic commands ###
