"""Added Property DB.Model

Revision ID: 97cb4eb3b502
Revises: 9a2bb0862363
Create Date: 2021-06-27 02:38:11.713046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97cb4eb3b502'
down_revision = '9a2bb0862363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_name', sa.String(length=100), nullable=False),
    sa.Column('property_description', sa.String(), nullable=False),
    sa.Column('property_price', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('property_images', sa.String(), nullable=True),
    sa.Column('property_features', sa.String(), nullable=True),
    sa.Column('property_owner', sa.Integer(), nullable=False),
    sa.Column('additionalContactInfo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['property_owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('property')
    # ### end Alembic commands ###
