"""User model

Revision ID: 9a2bb0862363
Revises: 
Create Date: 2021-06-13 17:39:35.950834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a2bb0862363'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_pword', sa.String(), nullable=False),
    sa.Column('user_updates', sa.Integer(), nullable=True),
    sa.Column('user_pic', sa.String(), nullable=True),
    sa.Column('user_phone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
