"""Added businessName Column -> Contact Card

Revision ID: f30a88f99f2f
Revises: 87d20ff10f5c
Create Date: 2021-07-03 00:13:50.285995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f30a88f99f2f'
down_revision = '87d20ff10f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('businessName', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'businessName')
    # ### end Alembic commands ###
